# About Project
name: offline_webview
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.19.6 <3.0.0"

# App Dependencies
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  webview_flutter: ^4.2.0
  path_provider: ^2.0.15
  permission_handler: ^10.2.0
  webview_flutter_android: ^3.7.0
  logger: ^1.3.0
  internet_connection_checker: ^1.0.0+1

# Dev Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# App Configs
flutter:
  uses-material-design: true
